In [1]:
import pandas as pd

# 创建数据字典
data = {
    '姓名': ['张三', '李四', '王五'],
    '年龄': [28, 34, 29],
    '城市': ['北京', '上海', '广州']
}

# 实例化 DataFrame
df = pd.DataFrame(data)

print("--- 基础 DataFrame ---")
print(df)

--- 基础 DataFrame ---
   姓名  年龄  城市
0  张三  28  北京
1  李四  34  上海
2  王五  29  广州


In [3]:
# 查看前 2 行数据
print("--- head() 预览 ---")
print(df.head(2))

print("\n--- info() 结构信息 ---")
df.info()

print("\n--- describe() 统计学描述 ---")
print(df.describe())

--- head() 预览 ---
   姓名  年龄  城市
0  张三  28  北京
1  李四  34  上海

--- info() 结构信息 ---
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      3 non-null      str  
 1   年龄      3 non-null      int64
 2   城市      3 non-null      str  
dtypes: int64(1), str(2)
memory usage: 240.0 bytes

--- describe() 统计学描述 ---
              年龄
count   3.000000
mean   30.333333
std     3.214550
min    28.000000
25%    28.500000
50%    29.000000
75%    31.500000
max    34.000000


In [4]:
import numpy as np
from scipy.sparse import csr_matrix

# 1. 模拟一个稀疏矩阵的底层存储
# 假设是一个 3x3 的矩阵，大部分是 0
data = np.array([1, 1, 1])
row = np.array([0, 1, 2])
col = np.array([0, 1, 0])
sparse_matrix = csr_matrix((data, (row, col)), shape=(3, 3))

print("--- 转换前（稀疏矩阵） ---")
print(sparse_matrix)

# 2. 使用 .toarray() 还原
dense_array = sparse_matrix.toarray()

print("\n--- 转换后（密集型二维数组） ---")
print(dense_array)

--- 转换前（稀疏矩阵） ---
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	1
  (1, 1)	1
  (2, 0)	1

--- 转换后（密集型二维数组） ---
[[1 0 0]
 [0 1 0]
 [1 0 0]]
