# 参数初始化

## 常数初始化

In [23]:
import torch.nn as nn

linear = nn.Linear(5, 2)

# 全部参数初始化为0
nn.init.zeros_(linear.weight)
print(linear.weight)

# 全部参数初始化为1
nn.init.ones_(linear.weight)
print(linear.weight)

# 全部参数初始化为一个常数
nn.init.constant_(linear.weight, 10)
print(linear.weight)

Parameter containing:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], requires_grad=True)
Parameter containing:
tensor([[10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10.]], requires_grad=True)


## 秩初始化

In [24]:
import torch.nn as nn

linear = nn.Linear(5, 2)

# 参数初始化为单位矩阵
nn.init.eye_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.]], requires_grad=True)


## 正态分布初始化

In [25]:
import torch.nn as nn

linear = nn.Linear(5, 2)

# 参数初始化为按指定均值与标准差正态分布
nn.init.normal_(linear.weight, mean=0.0, std=1.0)
print(linear.weight)

Parameter containing:
tensor([[ 0.1546,  1.0378,  0.6369, -1.0886,  0.5514],
        [-0.8224,  0.7636, -1.7631, -0.6408, -1.2081]], requires_grad=True)


## 均匀分布初始化

In [26]:
import torch.nn as nn

linear = nn.Linear(5, 2)

# 参数初始化为在区间内均匀分布
nn.init.uniform_(linear.weight, a=0, b=10)
print(linear.weight)

Parameter containing:
tensor([[0.6759, 8.8809, 5.4017, 1.1786, 3.9293],
        [1.7291, 7.4726, 7.6533, 9.1194, 1.5372]], requires_grad=True)


## Xavier初始化（Glorot初始化）

In [27]:
import torch.nn as nn

linear = nn.Linear(5, 2)

# Xavier正态分布初始化
nn.init.xavier_normal_(linear.weight)
print(linear.weight)

# Xavier均匀分布初始化
nn.init.xavier_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[-0.3965, -0.3904,  0.4584, -0.3713, -0.2807],
        [-0.8875,  0.1907,  0.7572, -0.4517,  0.9207]], requires_grad=True)
Parameter containing:
tensor([[ 0.0949,  0.2227, -0.5299, -0.1243,  0.0263],
        [ 0.7794,  0.2332,  0.7819,  0.8758, -0.3704]], requires_grad=True)


## He初始化（Kaiming初始化）

In [28]:
import torch.nn as nn

linear = nn.Linear(5, 2)

# Kaiming正态分布初始化
nn.init.kaiming_normal_(linear.weight)
print(linear.weight)

# Kaiming均匀分布初始化
nn.init.kaiming_uniform_(linear.weight)
print(linear.weight)

Parameter containing:
tensor([[ 0.5048, -0.8753, -0.4012, -0.3229, -1.0550],
        [ 0.1195,  1.2120, -0.1870, -0.4266, -0.4596]], requires_grad=True)
Parameter containing:
tensor([[-0.8325,  0.8194, -0.0610,  0.8449, -0.1598],
        [-1.0565,  0.2485,  0.0714,  0.9432,  0.7961]], requires_grad=True)


## Dropout 随机失活

In [29]:
import torch

dropout = torch.nn.Dropout(p=0.5)
x = torch.randint(1, 10, (10,), dtype=torch.float32)
print("Dropout前：", x)
print("Dropout后：", dropout(x))

Dropout前： tensor([3., 6., 9., 1., 3., 8., 4., 3., 6., 8.])
Dropout后： tensor([ 0., 12.,  0.,  2.,  6., 16.,  0.,  6.,  0.,  0.])
