In [5]:
import torch
import torch.nn as nn


class Model(nn.Module):
  # 初始化
  def __init__(self):
    super(Model, self).__init__()  # 调用父类初始化
    self.linear1 = nn.Linear(3, 4)  # 第1个隐藏层，3个输入，4个输出
    nn.init.xavier_normal_(self.linear1.weight)  # 初始化权重参数
    self.linear2 = nn.Linear(4, 4)  # 第2个隐藏层，4个输入，4个输出
    nn.init.kaiming_normal_(self.linear2.weight)  # 初始化权重参数
    self.out = nn.Linear(4, 2)  # 输出层，4个输入，2个输出，默认使用He均匀分布初始化

  # 前向传播
  def forward(self, x):
    x = self.linear1(x)  # 经过第1个隐藏层
    x = torch.tanh(x)  # 激活函数
    x = self.linear2(x)  # 经过第2个隐藏层
    x = torch.relu(x)  # 激活函数
    x = self.out(x)  # 经过输出层
    x = torch.softmax(x, dim=1)  # 激活函数
    return x


model = Model()
output = model(torch.randn(10, 3))
print("输出：\n", output)
print()

# 使用named_parameters()查看各层参数
print("模型参数：")
for name, param in model.named_parameters():
  print(name, param)
  print()

# 使用state_dict()查看各层参数
print("模型参数11：\n", model.state_dict())

输出：
 tensor([[0.3306, 0.6694],
        [0.2179, 0.7821],
        [0.2568, 0.7432],
        [0.3306, 0.6694],
        [0.3251, 0.6749],
        [0.2796, 0.7204],
        [0.2668, 0.7332],
        [0.2441, 0.7559],
        [0.3306, 0.6694],
        [0.3192, 0.6808]], grad_fn=<SoftmaxBackward0>)

模型参数：
linear1.weight Parameter containing:
tensor([[ 0.1885,  0.2641, -0.1169],
        [ 0.7470,  0.3139,  0.0175],
        [-0.1484, -0.6103, -0.3498],
        [-0.0987, -0.4105,  0.2362]], requires_grad=True)

linear1.bias Parameter containing:
tensor([0.4834, 0.2637, 0.4855, 0.4657], requires_grad=True)

linear2.weight Parameter containing:
tensor([[-0.3617,  1.3481, -0.4659,  0.8690],
        [-0.5297,  0.9422,  0.4930,  0.0673],
        [-1.1168, -0.8710, -0.9869,  0.4990],
        [-0.4546, -1.3647, -0.3042,  0.1056]], requires_grad=True)

linear2.bias Parameter containing:
tensor([-0.0562, -0.2459, -0.1788, -0.4693], requires_grad=True)

out.weight Parameter containing:
tensor([[-0.3805, 

In [7]:
from torchsummary import summary

# input_size:特征数，batch_size:样本数
summary(model, input_size=(3,), batch_size=10, device="cpu")

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                    [10, 4]              16
            Linear-2                    [10, 4]              20
            Linear-3                    [10, 2]              10
Total params: 46
Trainable params: 46
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


## 使用Sequential构建模型

In [8]:
# 构建模型
model = nn.Sequential(
  nn.Linear(3, 4),
  nn.Tanh(),
  nn.Linear(4, 4),
  nn.ReLU(),
  nn.Linear(4, 2),
  nn.Softmax(dim=1),
)


# 初始化参数
def init_weights(m):
  # 对Linear层进行初始化
  if type(m) == nn.Linear:
    nn.init.xavier_uniform_(m.weight)
    m.bias.data.fill_(0.01)


model.apply(init_weights)  # apply会遍历所有子模块并依次调用函数

output = model(torch.randn(10, 3))
print("输出：\n", output)

输出：
 tensor([[0.6403, 0.3597],
        [0.3556, 0.6444],
        [0.5751, 0.4249],
        [0.3716, 0.6284],
        [0.6218, 0.3782],
        [0.4395, 0.5605],
        [0.5702, 0.4298],
        [0.5290, 0.4710],
        [0.3522, 0.6478],
        [0.5922, 0.4078]], grad_fn=<SoftmaxBackward0>)
