## 二分类任务损失函数

二分类任务常用二元交叉熵损失函数（Binary Cross-Entropy Loss）

In [18]:
import torch

import torch.nn as nn

input = torch.randn(3, 1)

print(input)

target = torch.tensor([[1], [0], [0]], dtype=torch.float32)

predict = nn.Sigmoid()(input)

loss = nn.BCELoss()(predict, target)

print(loss)

tensor([[-0.2858],
        [ 0.4992],
        [-0.5943]])
tensor(0.7531)


## 多分类任务损失函数

In [19]:
import torch
import torch.nn as nn

# 真实值为标签
target = torch.tensor([1, 0, 3, 2, 5, 4])  # 真实值
input = torch.randn((6, 8))  # 预测值
print(input)
loss = nn.CrossEntropyLoss()  # 实例化损失函数
print(loss(input, target))

# 真实值为概率
target = torch.randn(6, 8).softmax(dim=1)  # 真实值
input = torch.randn((6, 8))  # 预测值
loss = nn.CrossEntropyLoss()  # 实例化损失函数
print(loss(input, target))

tensor([[-0.0216, -1.0041,  0.1328,  1.3479, -0.6151,  1.7691, -0.0428, -0.9275],
        [ 1.2197,  0.6811, -0.1276, -0.0053, -1.3994, -0.1944, -0.8587,  1.2830],
        [ 2.7888, -2.3830,  1.1961,  0.3554, -0.6140, -0.5194, -1.0702, -0.8249],
        [-0.0741, -0.7935,  0.0044, -0.6490, -0.6816,  2.3286,  1.0547, -0.4239],
        [-0.8114, -0.5253, -1.0580, -0.1827,  0.6479,  0.0840, -1.2498, -2.4954],
        [-0.8526, -0.7772, -0.2752, -0.8389,  0.9739, -2.5210,  1.1210, -0.5620]])
tensor(2.2266)
tensor(2.2274)


## 回归任务损失函数

In [20]:
import torch
import torch.nn as nn
import torch.optim as optim


class Model(nn.Module):
  def __init__(self):
    super(Model, self).__init__()
    # 1. 全连接层
    self.linear1 = nn.Linear(5, 3)

    # 2. 初始化权重 (原样保留)
    self.linear1.weight.data = torch.tensor(
      [
        [0.1, 0.2, 0.3],
        [0.4, 0.5, 0.6],
        [0.7, 0.8, 0.9],
        [0.10, 1.1, 1.2],
        [1.3, 1.4, 1.5],
      ],
      dtype=torch.float32
    ).T

    # 3. 初始化偏置 (原样保留)
    self.linear1.bias.data = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)

  def forward(self, x):
    return self.linear1(x)


# ==========================================
# 训练与测试流程
# ==========================================

# 1. 实例化模型
model = Model()

# 2. 准备数据
X = torch.tensor([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], dtype=torch.float32)
target = torch.tensor([[0, 0, 0], [0, 0, 0]], dtype=torch.float32)

# 3. 前向传播
output = model(X)

# 4. 损失函数
criterion = nn.MSELoss() # criterion：在英语中，“criterion” 的意思是“准则”或“标准”。在模型训练时，这个变量代表了我们衡量模型好坏的标准——即预测值与真实值之间的差距。
loss_val = criterion(output, target)

# 5. 反向传播
loss_val.backward()

# 6. 优化器更新参数
optimizer = optim.SGD(model.parameters(), lr=1)
optimizer.step()

# 7. 清空梯度
optimizer.zero_grad()

# 8. 打印更新后的参数
print("--- 更新后的模型参数 ---")
for name, param in model.state_dict().items():
  print(f"参数名称: {name}")
  print(param)
  print("-" * 30)

--- 更新后的模型参数 ---
参数名称: linear1.weight
tensor([[ -51.3333,  -62.6333,  -73.9333,  -86.1333,  -96.5333],
        [ -79.4667,  -97.1667, -114.8667, -132.5667, -150.2667],
        [ -90.2000, -110.4000, -130.6000, -150.8000, -171.0000]])
------------------------------
参数名称: linear1.bias
tensor([-10.6000, -16.0000, -17.5000])
------------------------------
