In [2]:
import torch

print(torch.__version__)

2.11.0


In [3]:
tensor1 = torch.tensor(10)

print(tensor1)
print(tensor1.size()) # torch.Size([])
print(tensor1.dtype)

tensor2 = torch.tensor([1, 2, 3, 4, 5])

print(tensor2)
print(tensor2.size()) # torch.Size([5])
print(tensor2.dtype) # torch.int64

tensor3 = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(tensor3)
print(tensor3.size()) # torch.Size([2, 3])
print(tensor3.dtype) # torch.int64

tensor4 = torch.tensor([1.0, 2.0, 3.0])

print(tensor4)
print(tensor4.size())
print(tensor4.dtype) # torch.float32




tensor(10)
torch.Size([])
torch.int64
tensor([1, 2, 3, 4, 5])
torch.Size([5])
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])
torch.int64
tensor([1., 2., 3.])
torch.Size([3])
torch.float32


In [ ]:
import numpy as np

tensor5 = torch.tensor(np.array([1, 2, 3, 4, 5]))

print(tensor5)
print(tensor5.size())
print(tensor5.dtype) # torch.int64


tensor6 = torch.tensor(np.array([1.0, 2.0, 3.0]))

print(tensor6)
print(tensor6.size())
print(tensor6.dtype) # torch.float64

tensor7 = torch.tensor(np.array([[1.0, 2, 3], [4, 5, 6]]))

print(tensor7)
print(tensor7.size())
print(tensor7.dtype) # torch.float64


tensor([1, 2, 3, 4, 5])
torch.Size([5])
torch.int64
tensor([1., 2., 3.], dtype=torch.float64)
torch.Size([3])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.Size([2, 3])
torch.float64


In [8]:
tensor8 = torch.Tensor(2,3,4)

print(tensor8)
print(tensor8.size())
print(tensor8.dtype)




tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])
torch.float32


In [19]:
test = torch.randint(1, 10, (2, 3))

print(test)

tensor([[5, 3, 4],
        [7, 9, 4]])
